config/routes.rb
Backchannel::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end
  get "admin/index"

  resources :comments

  resources :votes

  resources :users

  get "panel/index"

  get "panel/map"

  resources :posts

  match 'user/addadmin', :controller => 'users', :action => 'addadmin' 

  match 'panel/search', :controller => 'panel', :action => 'search' 

  match 'panel/index', :controller => 'panel', :action => 'index' 

  match 'user/rmvadmin', :controller => 'users', :action => 'rmvadmin' 

  root :to => 'sessions#new', :as => :new 
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessible :title, :body, :password_confirmation, :password, :name
  has_many :posts, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  validate :password_must_be_present
  private
  def password_must_be_present
	  errors.add(:password, "missing password") unless password.present?
  end

  def User.authenticate(name,password)
	  if user = find_by_name(name)
		  if user.password == password
			  user
		  end
	  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
    @cuser = current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
	session[:user_id] = @user.id
        format.html { redirect_to admin_url, notice: 'User was successfully created.' }

        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def addadmin 
    @user = User.find(params[:user])

    respond_to do |format|
      if @user.save
    @user.update_attribute('ifadmin', params[:admin]) 
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  


  def rmvadmin 
    @user = User.find(params[:user])

    respond_to do |format|
      if @user.save
    @user.update_attribute('ifadmin', params[:admin]) 
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
	  <legend>Enter User Details</legend>

  <div>
	  <%= f.label :name %>:
	  <%= f.text_field :name, :size => 40 %>
  </div>

  <div>
	  <%= f.label :password, 'Password' %>:
	  <%= f.password_field :password, :size => 40 %>
  </div>
  
  <div>
	  <%= f.label :password_confirmation, 'Confirm' %>:
	  <%= f.password_field :password_confirmation, :size => 40 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
	<p id="notice "><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>

    <% if user.ifadmin == true %>
    	<td><%= link_to 'Remove Admin', user_rmvadmin_path( :user => user, :admin => false ) %></td>
    <% else %>
    	<td><%= link_to 'Make Admin', user_addadmin_path( :user => user, :admin => true ) %></td>
    <% end %>

    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% if user.id != @cuser.id %>
   	 <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>