config/routes.rb
Backchannel::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end
  get "admin/index"

  resources :comments

  resources :votes

  resources :users

  get "panel/index"

  get "panel/map"

  resources :posts

  match 'user/addadmin', :controller => 'users', :action => 'addadmin' 

  match 'panel/search', :controller => 'panel', :action => 'search' 

  match 'panel/index', :controller => 'panel', :action => 'index' 

  match 'user/rmvadmin', :controller => 'users', :action => 'rmvadmin' 

  root :to => 'sessions#new', :as => :new 
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope :order => 'updated_at DESC'
  attr_accessible :content, :title, :user_id, :category
  validates :title, :content, :category,  :presence =>true
  has_many :votes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  belongs_to :user
  def add_user(user_id)
	  current_item=votes.find_by_user_id(user_id)
	  if current_item
		  current_item.quantity +=1
	  else
		  current_item = votes.build(:user_id => user_id)
	  end
	  current_item
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.all
    @post = Post.find(params[:id])
    @user = current_user
    @vote = Vote.group("user_id").where(["post_id = ?",params[:id]]).all
   

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @user= current_user

    respond_to do |format|
      if @post.save
	 @post.update_attribute("user_id",@user.id)
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select($category) %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/error.html.erb
<p id="notice"><%= notice %></p>

<p> error: you already vote for it</p>
<br/>
<%= link_to 'Back', panel_path %>

app/views/posts/index.html.erb
<div id="product_list">
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>category</th>
    <th>Content</th>
    <th>User Id</th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= post.title %></td>
    <td><%= post.category %></td>
    <td><%= post.content %></td>
    <% @tuser = User.find(post.user_id) %>
    <td><%= @tuser.name %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="product_list">

<table class="show_panel">
  <tr>
    <th>Title</th>
    <th>category</th>
    <th>User</th>
    <th>Content</th>
    <th>Vote</th>
  </tr>

  <tr><td><hr></td><td><hr></td><td><hr></td><td><hr></td><td><hr></td></tr>
  
  <tr>
    <td><%= @post.title %></td>
    <td><%= @post.category %></td>
    <% @tuser = User.find(@post.user_id) %>
    <td><%= @tuser.name %></td>
    <td><%= @post.content %></td>
    <td><%= @post.votenum %></td>
  </tr>

  <tr><td><hr></td><td><hr></td><td><hr></td><td><hr></td><td><hr></td></tr>
  <tr><td></td></tr>
  <tr><td></td></tr>
  <tr>
	  <th>User</th>
	  <th>Comments:</th>
	  <th>Vote</th>
  </tr>

  <% @comments.each do |comment| %>
	<% if comment.post_id == @post.id %>
		<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
		<% @tuser = User.find(comment.user_id) %>
  		<td><%= @tuser.name %></td>
   	 	<td><%= comment.content %></td>
		<td><%= comment.votenum %></td>
		<% if @user.id != comment.user_id %>
			<td><%= button_to 'vote', votes_path(:comment => comment, :ifpost => 0, :post => @post, :comment_id => comment.id)  %></td>
		<% else %>
			<td><%= button_to 'vote', votes_path(:comment => comment, :ifpost => 0, :post => @post, :comment_id => comment.id), :disabled => true  %></td>
		<% end %>
		<% if @user.id == comment.user_id || session[:ifadmin] == true %>
			<td><%= link_to 'Edit', edit_comment_path(comment) %></td>
			<td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% else %>
			<td></td>
			<td></td>
		<% end %>
		</tr>
	<% end %>
<% end %>

  <tr><td><%= link_to 'Make a Comment', new_comment_path(:post_id => @post) %></td></tr>
  <tr><td></td></tr>
  <tr>
	<th>People who voted this post</th>
  </tr>
	  <tr>
  		  <% @vote.each do |vote| %>
	 	  <% @fuser=User.find(vote.user_id) %>
		  <td><%= @fuser.name %></td>
	  </tr>
  <% end %>


</table>
</div>


<% if @user.id == @post.user_id %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<% if @user.ifadmin == true %>
	<%= link_to 'Back', posts_path %>
<% else %>
	<%= link_to 'Back', panel_index_path %>
<% end %>