config/routes.rb
Backchannel::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end
  get "admin/index"

  resources :comments

  resources :votes

  resources :users

  get "panel/index"

  get "panel/map"

  resources :posts

  match 'user/addadmin', :controller => 'users', :action => 'addadmin' 

  match 'panel/search', :controller => 'panel', :action => 'search' 

  match 'panel/index', :controller => 'panel', :action => 'index' 

  match 'user/rmvadmin', :controller => 'users', :action => 'rmvadmin' 

  root :to => 'sessions#new', :as => :new 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backchannel</title>
  <%= stylesheet_link_tag    "backchannel","application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
	<div id="banner">
		<%= @page_title || "Post Panel" %>
	</div>
	<div id="columns">
		<div id="side">
			<%= link_to'Home', panel_index_path %><br/>
			<%= link_to'FAQ', panel_map_path %><br/>
			<%= link_to'Contact', "http://www4.ncsu.edu/~yliu63/index.html" %><br/>
			<% if session[:user_id] %>
				<% if session[:ifadmin] == true %>
					<br/>
					<%= link_to 'Posts', posts_path %><br/>
					<%= link_to 'Users', users_path %><br/>
					<br/>
					<%= button_to 'Logout', logout_path, :method => :delete %>
				<% else %>
					<br/>
					<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>

			<% else %>
				<%= link_to 'Login', login_path %><br/>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
</body>
</html>